apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qantara
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: qantara
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: tls-tnd-bankdhofar-com
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /open-banking/
            pathType: Prefix
            backend:
              service:
                name: ob-api-server
                port:
                  number: 8000
          - path: /portal-api/
            pathType: Prefix
            backend:
              service:
                name: ob-tpp-manager
                port:
                  number: 8000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: ob-api-server
                port:
                  number: 8000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: ob-api-server
                port:
                  number: 8000
          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: ob-api-server
                port:
                  number: 8000
          - path: /openapi.json
            pathType: Exact
            backend:
              service:
                name: ob-api-server
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ob-portal
                port:
                  number: 80
